#!/usr/bin/env python3
import sys
import os
import socket
import struct
import time
import signal
from Foundation import NSObject, NSData, NSRunLoop
from CoreBluetooth import (
    CBPeripheralManager,
    CBManagerStatePoweredOn,
    CBAdvertisementDataLocalNameKey,
    CBAdvertisementDataManufacturerDataKey
)
import objc

# Path to the file UxPlay generates
BLE_FILE_PATH = os.path.expanduser("~/.uxplay.ble")

def get_local_ip():
    """Get the active local IPv4 address."""
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        # Doesn't actually connect, just determines the route
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
    except Exception:
        ip = "127.0.0.1"
    finally:
        s.close()
    return ip

def get_uxplay_port():
    """Read the port from the .uxplay.ble file generated by UxPlay."""
    if not os.path.exists(BLE_FILE_PATH):
        print(f"Error: {BLE_FILE_PATH} not found.")
        print("Make sure UxPlay is running with the '-ble' flag.")
        return None
    
    with open(BLE_FILE_PATH, "r") as f:
        content = f.read().strip()
        # The file contains: port\npid\nprocess_name
        try:
            return int(content.splitlines()[0])
        except ValueError:
            print("Error: Could not parse port from .uxplay.ble")
            return None

class BeaconDelegate(NSObject):
    def peripheralManagerDidUpdateState_(self, manager):
        state = manager.state()
        if state == CBManagerStatePoweredOn:
            print("Bluetooth is ON. Preparing beacon...")
            self.start_advertising(manager)
        else:
            print(f"Bluetooth state changed: {state} (Not Powered On)")

    def start_advertising(self, manager):
        port = get_uxplay_port()
        if not port:
            print("Waiting for UxPlay to start...")
            # Ideally retry, but for simplicity we exit or wait
            return

        ip_str = get_local_ip()
        print(f"Broadcasting for UxPlay @ {ip_str}:{port}")

        # --- Construct the AirPlay Beacon Packet ---
        # 1. Company ID: Apple (0x004C) - Required for AirPlay
        company_id = struct.pack(">H", 0x004C) 
        
        # 2. AirPlay Data Structure
        # 0x09 = Type (AirPlay)
        # 0x08 = Length of remaining data (Magic + IP + Port = 2 + 4 + 2 = 8 bytes)
        prefix = b'\x09\x08'
        
        # 3. Magic Bytes (0x1330) - Identifies this as an AirPlay target
        magic = b'\x13\x30'
        
        # 4. IP Address (4 bytes)
        ip_bytes = socket.inet_aton(ip_str)
        
        # 5. Port (2 bytes, Big Endian)
        port_bytes = struct.pack(">H", port)
        
        # Combine payload
        # CoreBluetooth requires the Manufacturer Data to be wrapped in NSData
        # Note: We prepend company_id because macOS might not auto-insert it 
        # inside the manufacturer specific data payload for custom packets.
        full_payload = company_id + prefix + magic + ip_bytes + port_bytes
        
        payload_nsdata = NSData.dataWithBytes_length_(full_payload, len(full_payload))
        
        # Advertisement Dictionary
        adv_data = {
            CBAdvertisementDataLocalNameKey: "UxPlay",
            CBAdvertisementDataManufacturerDataKey: payload_nsdata
        }
        
        manager.startAdvertising_(adv_data)
        print("Beacon active. Press Ctrl+C to stop.")

    def peripheralManagerDidStartAdvertising_error_(self, manager, error):
        if error:
            print(f"Failed to advertise: {error}")
        else:
            print("Successfully started advertising!")

def main():
    delegate = BeaconDelegate.alloc().init()
    manager = CBPeripheralManager.alloc().initWithDelegate_queue_(delegate, None)
    
    print(f"Monitoring {BLE_FILE_PATH}...")
    
    try:
        # Run the standard macOS Event Loop
        NSRunLoop.currentRunLoop().run()
    except KeyboardInterrupt:
        pass

if __name__ == "__main__":
    # Ensure dependencies are met
    try:
        import CoreBluetooth
    except ImportError:
        print("Error: Required libraries not found.")
        print("Please run: pip install pyobjc-framework-CoreBluetooth")
        sys.exit(1)
        
    main()